# 2. Write Python code to complete each of the tasks listed below.

In [48]:
import numpy as np

(a) Generate a 4*4 matrix, A, consisting entirely of ones.

In [49]:
A = np.ones((4,4), dtype=float)
print("(a) = ", A)

(a) =  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


(b) Modify A so that all elements in its second column are replaced with the value 5.

In [50]:
A[:, 1] = 5
print("(b) = ", A)

(b) =  [[1. 5. 1. 1.]
 [1. 5. 1. 1.]
 [1. 5. 1. 1.]
 [1. 5. 1. 1.]]


(c) Compute the sum of each row in A and store the results in a one-dimensional array s.

In [51]:
s = A.sum(axis=1)
print("(c) = ", s)

(c) =  [8. 8. 8. 8.]


(d) Append s as the last column of A to make it a matrix with 5 columns.

In [52]:
A = np.column_stack([A, s])
print("(d) = ", A)

(d) =  [[1. 5. 1. 1. 8.]
 [1. 5. 1. 1. 8.]
 [1. 5. 1. 1. 8.]
 [1. 5. 1. 1. 8.]]


(e) Transpose the updated matrix A (A = AT)

In [53]:
A = A.T
print ("(e) A = ", A)

(e) A =  [[1. 1. 1. 1.]
 [5. 5. 5. 5.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [8. 8. 8. 8.]]


(f) Generate a matrix B such that 
1) its first row contains the standard deviation of each row of A, and 
2) the second row contains random numbers drawn uniformly from [0, 1]. Use np.random.seed(2025) for reproducibility.

In [54]:
row_first = np.std(A, axis=1, ddof=0)
np.random.seed(2025)
row_second = np.random.uniform(0, 1, size=A.shape[0])
B = np.vstack([row_first, row_second])
print("(f) B = ", B)

(f) B =  [[0.         0.         0.         0.         0.        ]
 [0.13548816 0.8878517  0.93260564 0.44556816 0.38823555]]


(g) Compute the matrix product: C = B*A

In [55]:
C = B @ A
print("(g) C = ", C)

(g) C =  [[0.         0.         0.         0.        ]
 [9.05880485 9.05880485 9.05880485 9.05880485]]


(h) Let X = [2,4,6,8].T, Y = [12, 9, 6, 3].T, Z = [5, 10, 15, 10].T.
Compute the variance of each vector seperately, and then calculate the Pearson correlation coefficient between X and Y.

In [56]:
X = np.array([2, 4, 6, 8], dtype = float)
Y = np.array([12, 9, 6, 3], dtype = float)
Z = np.array([5, 10, 15, 10], dtype = float)

var_X = np.var(X, ddof = 0)
var_Y = np.var(Y, ddof = 0)
var_Z = np.var(Z, ddof = 0)

Pearcorr_XY = np.corrcoef(X, Y)[0, 1]

print("(h) variance X = ", var_X)
print("(h) variance Y = ", var_Y)
print("(h) variance Z = ", var_Z)
print("(h) Pearson correlation coefficient = ", Pearcorr_XY)

(h) variance X =  5.0
(h) variance Y =  11.25
(h) variance Z =  12.5
(h) Pearson correlation coefficient =  -1.0


(i) Let x = [8, 15, 10, 12, 20, 18, 14].T.
Verify the equation: x_bar_squa = (x_bar_squa + sigma_bar_squa(x)) for the two cases:
i) sigma(x) is the popluation standard deviation.
ii) sigam(x) is the sample standard deviation.
In both cases, show detailed calculations and justify the results using Python 

In [57]:
x = np.array([8, 15, 10, 12, 20, 18, 14], dtype = float)

x_bar = np.mean(x)
x_bar_squa = np.mean(x**2)

## i) popluation standard deviation ##
var_pop = np.var(x, ddof = 0)
result_pop = x_bar**2 + var_pop

## ii) sample standard deviation ##
var_sam = np.var(x, ddof = 1)
result_sam = x_bar**2 + var_sam

print("x_bar_squa = ", x_bar_squa)
print("(i).  i) = ", result_pop)
print("(i). ii) = ", result_sam)

x_bar_squa =  207.57142857142858
(i).  i) =  207.57142857142858
(i). ii) =  210.16326530612247


The equality holds when using the population variance, but not when using the sample variance.